# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sarp Kavalcioglu
tagline:          ''
description:      'Personal website for Sarp Kavalcioglu'
url:              http://hyde.getpoole.com
baseurl:          

author:
  name:           'Sarp Kavalcioglu'
  url:            https://www.linkedin.com/in/sarp-kavalcioglu/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kavalcio
